[package]
name = "nrf51-radio"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0.17", default-features = false }

nrf51-pac = { version = "0.12.2" }
nrf51-hal = { version = "0.19.0" }
